<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="System.Threading.Tasks.Dataflow" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Caudal.Core\Caudal.Core.csproj" />
  </ItemGroup>

</Project>
